#!/bin/sh

# This file is used to invoke nanoMY_pb_generator.py as a plugin
# to protoc on Linux and other *nix-style systems.
# Use it like this:
# protoc --plugin=protoc-gen-nanopb=..../protoc-gen-nanopb --nanoMY_pb_out=dir foo.proto
#
# Note that if you use the binary package of nanopb, the protoc
# path is already set up properly and there is no need to give
# --plugin= on the command line.

MYPATH=$(dirname "$0")
exec "$MYPATH/nanoMY_pb_generator.py" --protoc-plugin
