#ifndef __EEPROM_ADDRESSES_H__
#define __EEPROM_ADDRESSES_H__

#define DEVICE_ID_MEM_ADDRESS                   (0)
#define CO2_ZERO_MEM_ADDRESS                    (4)
#define CO2_SLOPE_MEM_ADDRESS                   (8)
#define CO_ZERO_MEM_ADDRESS                     (12)
#define CO_SLOPE_MEM_ADDRESS                    (16)
#define PM_1_ZERO_MEM_ADDRESS                   (20)
#define PM_1_SLOPE_MEM_ADDRESS                  (24)
#define PM_25_ZERO_MEM_ADDRESS                  (28)
#define PM_25_SLOPE_MEM_ADDRESS                 (32)
#define PM_10_ZERO_MEM_ADDRESS                  (36)
#define PM_10_SLOPE_MEM_ADDRESS                 (40)
#define TEMP_ZERO_MEM_ADDRESS                   (44)
#define TEMP_SLOPE_MEM_ADDRESS                  (48)
#define PRESSURE_ZERO_MEM_ADDRESS               (52)
#define PRESSURE_SLOPE_MEM_ADDRESS              (56)
#define RH_ZERO_MEM_ADDRESS                     (60)
#define RH_SLOPE_MEM_ADDRESS                    (64)
#define CELLULAR_EN_MEM_ADDRESS                 (68)
#define DEBUGGING_ENABLED_MEM_ADDRESS           (72)
#define GAS_LOWER_LIMIT_MEM_ADDRESS             (76)
#define GAS_UPPER_LIMIT_MEM_ADDRESS             (80)
#define TIME_ZONE_MEM_ADDRESS                   (84)
#define OZONE_EN_MEM_ADDRESS                    (88)
#define VOC_EN_MEM_ADDRESS                      (92)
#define TEMPERATURE_UNITS_MEM_ADDRESS           (96)
#define OUTPUT_PARTICLES_MEM_ADDRESS            (100)
#define TEMPERATURE_SENSOR_ENABLED_MEM_ADDRESS  (104)
#define OZONE_A_OR_D_MEM_ADDRESS                (108)
#define OZONE_OFFSET_MEM_ADDRESS                (112)
#define MEASUREMENTS_TO_AVG_MEM_ADDRESS         (116)
#define BATTERY_THRESHOLD_ENABLE_MEM_ADDRESS    (120)
#define ABC_ENABLE_MEM_ADDRESS                  (124)
#define HIH8120_ENABLE_MEM_ADDRESS              (128)
#define CO_SOCKET_MEM_ADDRESS                   (132)

#define VOC_SLOPE_MEM_ADDRESS                   (140)
#define VOC_ZERO_MEM_ADDRESS                    (144)

#endif // __EEPROM_ADDRESS_H__