/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "final_pam_upload.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SystemManifest, SystemManifest, AUTO)


PB_BIND(SystemTopology, SystemTopology, AUTO)


PB_BIND(SystemSettings, SystemSettings, AUTO)


PB_BIND(Calibration, Calibration, AUTO)


PB_BIND(SubSystem, SubSystem, AUTO)


PB_BIND(Device, Device, AUTO)


PB_BIND(Diagnostic, Diagnostic, AUTO)


PB_BIND(Upload, Upload, AUTO)


PB_BIND(DataPoint, DataPoint, AUTO)






