/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "pam.pb.h"
#if MY_PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanoMY_PB generator.
#endif

MY_PB_BIND(SystemManifest, SystemManifest, 4)


MY_PB_BIND(SystemTopology, SystemTopology, 2)


MY_PB_BIND(SystemSettings, SystemSettings, 2)


MY_PB_BIND(Calibration, Calibration, AUTO)


MY_PB_BIND(SubSystem, SubSystem, 2)


MY_PB_BIND(Device, Device, AUTO)


MY_PB_BIND(Diagnostic, Diagnostic, AUTO)


MY_PB_BIND(Upload, Upload, 2)


MY_PB_BIND(DataPoint, DataPoint, AUTO)






