/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef MY_PB_PAM_UPLOAD_MY_PB_H_INCLUDED
#define MY_PB_PAM_UPLOAD_MY_PB_H_INCLUDED
#include "MY_pb.h"

#if MY_PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _GPS_V { 
    double lat; 
    double long_; /* "long" is a reserved keyword in most languages */
    double acc; 
} GPS_V;

typedef struct _Upload { 
    uint32_t device_id; 
    float co; 
    float co2; 
    float no2; 
    uint32_t pm01; 
    float pm25; 
    float pm10; 
    float temp; 
    float press; 
    float hum; 
    float o3; 
    float batt; 
    bool has_gps;
    GPS_V gps; 
    uint32_t epoch; 
    bool sensible; 
} Upload;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Upload_init_default                      {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, false, GPS_V_init_default, 0, 0}
#define GPS_V_init_default                       {0, 0, 0}
#define Upload_init_zero                         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, false, GPS_V_init_zero, 0, 0}
#define GPS_V_init_zero                          {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define GPS_V_lat_tag                            1
#define GPS_V_long__tag                          2
#define GPS_V_acc_tag                            3
#define Upload_device_id_tag                     1
#define Upload_co_tag                            2
#define Upload_co2_tag                           3
#define Upload_no2_tag                           4
#define Upload_pm01_tag                          5
#define Upload_pm25_tag                          6
#define Upload_pm10_tag                          7
#define Upload_temp_tag                          8
#define Upload_press_tag                         9
#define Upload_hum_tag                           10
#define Upload_o3_tag                            11
#define Upload_batt_tag                          12
#define Upload_gps_tag                           13
#define Upload_epoch_tag                         14
#define Upload_sensible_tag                      15

/* Struct field encoding specification for nanopb */
#define Upload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   device_id,         1) \
X(a, STATIC,   SINGULAR, FLOAT,    co,                2) \
X(a, STATIC,   SINGULAR, FLOAT,    co2,               3) \
X(a, STATIC,   SINGULAR, FLOAT,    no2,               4) \
X(a, STATIC,   SINGULAR, UINT32,   pm01,              5) \
X(a, STATIC,   SINGULAR, FLOAT,    pm25,              6) \
X(a, STATIC,   SINGULAR, FLOAT,    pm10,              7) \
X(a, STATIC,   SINGULAR, FLOAT,    temp,              8) \
X(a, STATIC,   SINGULAR, FLOAT,    press,             9) \
X(a, STATIC,   SINGULAR, FLOAT,    hum,              10) \
X(a, STATIC,   SINGULAR, FLOAT,    o3,               11) \
X(a, STATIC,   SINGULAR, FLOAT,    batt,             12) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gps,              13) \
X(a, STATIC,   SINGULAR, UINT32,   epoch,            14) \
X(a, STATIC,   SINGULAR, BOOL,     sensible,         15)
#define Upload_CALLBACK NULL
#define Upload_DEFAULT NULL
#define Upload_gps_MSGTYPE GPS_V

#define GPS_V_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   lat,               1) \
X(a, STATIC,   SINGULAR, DOUBLE,   long_,             2) \
X(a, STATIC,   SINGULAR, DOUBLE,   acc,               3)
#define GPS_V_CALLBACK NULL
#define GPS_V_DEFAULT NULL

extern const MY_pb_msgdesc_t Upload_msg;
extern const MY_pb_msgdesc_t GPS_V_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Upload_fields &Upload_msg
#define GPS_V_fields &GPS_V_msg

/* Maximum encoded size of messages (where known) */
#define GPS_V_size                               27
#define Upload_size                              99

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
