/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "pam_upload.pb.h"
#if MY_PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

MY_PB_BIND(SystemManifest, SystemManifest, AUTO)


MY_PB_BIND(SystemTopology, SystemTopology, AUTO)


MY_PB_BIND(SystemSettings, SystemSettings, AUTO)


MY_PB_BIND(Calibration, Calibration, AUTO)


MY_PB_BIND(SubSystem, SubSystem, AUTO)


MY_PB_BIND(Device, Device, AUTO)


MY_PB_BIND(Diagnostic, Diagnostic, AUTO)


MY_PB_BIND(Upload, Upload, AUTO)


MY_PB_BIND(DataPoint, DataPoint, AUTO)






