/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "pam_upload.pb.h"
#if MY_PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

MY_PB_BIND(Upload, Upload, AUTO)


MY_PB_BIND(GPS_V, GPS_V, AUTO)



#ifndef MY_PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define MY_PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
MY_PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

